# Generated by Django 6.0.1 on 2026-01-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
