# Generated by Django 6.0.1 on 2026-01-30 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categorymodel_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='expriy_data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='manufacture_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
