# Generated by Django 6.0.1 on 2026-01-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productmodel_expriy_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='expriy_data',
            new_name='expiry_data',
        ),
    ]
