# Generated by Django 6.0.1 on 2026-01-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_expriy_data_productmodel_expiry_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='expiry_data',
            new_name='expiry_date',
        ),
    ]
