# Generated by Django 6.0.1 on 2026-01-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_expiry_data_productmodel_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='manufacture_date',
            field=models.DateField(),
        ),
    ]
