# Generated by Django 6.0.1 on 2026-01-31 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('add', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('payment_mode', models.CharField(max_length=20)),
                ('transaction', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Completed')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registrationmodel')),
            ],
        ),
    ]
