# Generated by Django 6.0.1 on 2026-01-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_ordermodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='add',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='pincode',
            new_name='zipcode',
        ),
    ]
