# Generated by Django 6.0.1 on 2026-02-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_add_ordermodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
