# Generated by Django 6.0.1 on 2026-02-01 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_ordermodel_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productmodel'),
        ),
    ]
