# Generated by Django 6.0.1 on 2026-03-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_ordermodel_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='qty',
        ),
        migrations.CreateModel(
            name='orderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ordermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productmodel')),
            ],
        ),
    ]
