# Generated by Django 6.0.1 on 2026-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_ordermodel_payment_status_productmodel_buy_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
